In [37]:
from numpy.random import seed
seed(1)
import numpy as np
import pandas as pd
import tensorflow
tensorflow.keras.__version__
import matplotlib.pyplot as plt
from matplotlib import style
style.use("ggplot")
from sklearn import tree

In [38]:
# read data
fires_df = pd.read_csv("data/forestfires.csv")
fires_df.head()

X  Y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area
0  7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0
1  7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0
2  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0
3  8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0
4  8  6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0

In [39]:
X = fires_df.drop(columns=["month", "day"])
y = fires_df["month"].values.reshape(-1,1)
print(X.shape, y.shape)

(517, 11) (517, 1)


In [40]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from tensorflow.keras.utils import to_categorical

In [41]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, random_state=1)

In [42]:
X_scaler = MinMaxScaler().fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [43]:
#LABEL ENCODER AATEMPT 
label_encoder = LabelEncoder()
label_encoder.fit(y_train)
encoded_y_train = label_encoder.transform(y_train)
encoded_y_test = label_encoder.transform(y_test)

In [44]:
list(encoded_y_train)

[6,
 1,
 11,
 1,
 11,
 11,
 1,
 11,
 1,
 11,
 7,
 0,
 7,
 1,
 11,
 11,
 7,
 11,
 1,
 7,
 1,
 1,
 11,
 11,
 7,
 1,
 11,
 7,
 1,
 7,
 1,
 2,
 1,
 11,
 1,
 11,
 7,
 11,
 1,
 5,
 11,
 1,
 11,
 1,
 5,
 1,
 11,
 7,
 1,
 1,
 11,
 1,
 1,
 7,
 1,
 7,
 1,
 7,
 11,
 10,
 1,
 4,
 3,
 1,
 1,
 6,
 11,
 11,
 9,
 11,
 1,
 5,
 7,
 1,
 1,
 11,
 1,
 5,
 3,
 11,
 11,
 11,
 11,
 11,
 11,
 7,
 11,
 1,
 11,
 1,
 11,
 3,
 1,
 11,
 5,
 7,
 1,
 11,
 11,
 11,
 0,
 7,
 2,
 7,
 11,
 7,
 3,
 1,
 1,
 11,
 11,
 11,
 11,
 7,
 11,
 1,
 5,
 10,
 6,
 8,
 6,
 11,
 1,
 1,
 1,
 1,
 7,
 1,
 1,
 5,
 5,
 1,
 11,
 1,
 11,
 5,
 1,
 1,
 1,
 1,
 1,
 11,
 11,
 1,
 7,
 1,
 1,
 1,
 1,
 11,
 1,
 2,
 1,
 1,
 11,
 1,
 11,
 11,
 1,
 11,
 1,
 1,
 1,
 1,
 11,
 11,
 1,
 1,
 1,
 7,
 11,
 5,
 1,
 11,
 1,
 11,
 1,
 7,
 1,
 11,
 11,
 11,
 1,
 1,
 11,
 11,
 1,
 11,
 6,
 1,
 7,
 11,
 6,
 11,
 1,
 11,
 11,
 11,
 1,
 1,
 11,
 7,
 6,
 7,
 11,
 1,
 1,
 11,
 11,
 11,
 11,
 5,
 3,
 1,
 5,
 11,
 10,
 7,
 7,
 2,
 7,
 0,
 11,
 11,
 1,
 0,
 11,
 1,
 11,
 1

In [45]:
# Convert encoded labels to one-hot-encoding
y_train_categorical = to_categorical(encoded_y_train)
y_test_categorical = to_categorical(encoded_y_test)

In [46]:
label_encoder.inverse_transform([0])

array(['apr'], dtype=object)

In [47]:
list(y_train_categorical)

array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.], dtype=float32),
 array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32),
 array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.], dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.], dtype=float32),
 array([0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.], dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.], dtype=float32),
 array([0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.], dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.], dtype=float32),
 array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32),
 array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32),
 array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32),
 array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 

In [48]:
from sklearn.svm import SVC 
model = SVC(kernel='rbf')

In [49]:
from sklearn.model_selection import GridSearchCV
param_grid = {'C': [1, 5, 10],
              'gamma': [0.0001, 0.001, 0.01]}
grid = GridSearchCV(model, param_grid, verbose=3)

In [62]:
grid.fit(X_train, y_train)

Fitting 5 folds for each of 9 candidates, totalling 45 fits
[CV] C=1, gamma=0.0001 ...............................................
[CV] ................... C=1, gamma=0.0001, score=0.833, total=   0.0s
[CV] C=1, gamma=0.0001 ...............................................
[CV] ................... C=1, gamma=0.0001, score=0.885, total=   0.0s
[CV] C=1, gamma=0.0001 ...............................................
[CV] ................... C=1, gamma=0.0001, score=0.883, total=   0.0s
[CV] C=1, gamma=0.0001 ...............................................
[CV] ................... C=1, gamma=0.0001, score=0.844, total=   0.0s
[CV] C=1, gamma=0.0001 ...............................................
[CV] ................... C=1, gamma=0.0001, score=0.857, total=   0.0s
[CV] C=1, gamma=0.001 ................................................
[CV] .................... C=1, gamma=0.001, score=0.859, total=   0.0s
[CV] C=1, gamma=0.001 ................................................
[CV] ............

GridSearchCV(cv=None, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid={'C': [1, 5, 10], 'gamma': [0.0001, 0.001, 0.01]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=3)

In [63]:
grid.best_params_

{'C': 10, 'gamma': 0.0001}

In [86]:
predictions = grid.predict(X_test)
predictions

array(['aug', 'aug', 'sep', 'sep', 'sep', 'jul', 'sep', 'jul', 'jul',
       'sep', 'aug', 'sep', 'mar', 'aug', 'sep', 'sep', 'sep', 'sep',
       'aug', 'jun', 'sep', 'aug', 'sep', 'aug', 'sep', 'sep', 'sep',
       'sep', 'aug', 'jun', 'sep', 'jul', 'jul', 'sep', 'sep', 'sep',
       'sep', 'sep', 'aug', 'aug', 'sep', 'mar', 'sep', 'aug', 'aug',
       'aug', 'aug', 'mar', 'sep', 'sep', 'aug', 'aug', 'sep', 'jun',
       'jul', 'aug', 'sep', 'aug', 'aug', 'aug', 'aug', 'sep', 'sep',
       'mar', 'oct', 'aug', 'aug', 'sep', 'feb', 'aug', 'aug', 'jul',
       'jul', 'mar', 'aug', 'aug', 'aug', 'sep', 'mar', 'aug', 'aug',
       'jul', 'aug', 'feb', 'mar', 'mar', 'oct', 'aug', 'sep', 'sep',
       'aug', 'jul', 'mar', 'sep', 'mar', 'feb', 'aug', 'mar', 'aug',
       'aug', 'sep', 'sep', 'aug', 'sep', 'aug', 'sep', 'jul', 'feb',
       'aug', 'feb', 'feb', 'aug', 'sep', 'sep', 'sep', 'aug', 'aug',
       'aug', 'aug', 'sep', 'sep', 'sep', 'jun', 'aug', 'sep', 'mar',
       'jul', 'dec',

In [103]:
prediction_df = pd.DataFrame(data=predictions, columns=['X_test'], 
                            index=y_test)
prediction_df


X_test
(aug,)    aug
(aug,)    aug
(sep,)    sep
(sep,)    sep
(sep,)    sep
...       ...
(mar,)    mar
(jul,)    jul
(dec,)    dec
(aug,)    sep
(aug,)    aug

[130 rows x 1 columns]

In [97]:
prediction_df.to_csv('month_predictions.csv', index=False) 

In [ ]:
prediction_df = pd.DataFrame({
    'predicted':predictions,
    'actual_y':y_test,
    'temp':X_test['temp']
})
prediction_df

In [91]:
predicted_df = pd.DataFrame(data=predictions, columns=['y_test'], 
                            index=X_test.index.copy())
df_out = pd.merge(X_test, predicted_df, how ='left', left_index=True, 
                 right_index=True)
df_out

X  Y  FFMC    DMC     DC   ISI  temp  RH  wind  rain   area y_test
270  2  2  92.1  152.6  658.2  14.3  21.8  56   3.1   0.0   0.52    aug
90   6  5  90.2   96.9  624.2   8.9  14.7  59   5.8   0.0   0.00    aug
133  4  6  93.7   80.9  685.2  17.9  17.6  42   3.1   0.0   0.00    sep
221  3  4  93.3  141.2  713.9  13.9  18.6  49   3.6   0.0  35.88    sep
224  7  4  90.1   82.9  735.7   6.2  15.4  57   4.5   0.0  37.71    sep
..  .. ..   ...    ...    ...   ...   ...  ..   ...   ...    ...    ...
18   6  4  89.2   27.9   70.8   6.3  15.9  35   4.0   0.0   0.00    mar
40   4  4  79.5   60.6  366.7   1.5  23.3  37   3.1   0.0   0.00    jul
273  4  6  84.4   27.2  353.5   6.8   4.8  57   8.5   0.0   8.98    dec
503  2  4  94.5  139.4  689.1  20.0  29.2  30   4.9   0.0   1.95    sep
500  8  6  96.1  181.1  671.2  14.3  21.6  65   4.9   0.8   0.00    aug

[130 rows x 12 columns]

In [83]:
df_out.to_csv('out.csv', index=False) 

In [64]:
grid.score(X_test, y_test)

0.9230769230769231

In [105]:
from sklearn.metrics import classification_report
print(classification_report(y_test, predictions))

precision    recall  f1-score   support

         apr       0.00      0.00      0.00         1
         aug       0.98      0.92      0.95        49
         dec       1.00      1.00      1.00         1
         feb       0.83      0.83      0.83         6
         jul       0.67      0.80      0.73        10
         jun       0.75      0.60      0.67         5
         mar       0.92      1.00      0.96        11
         oct       1.00      1.00      1.00         2
         sep       0.96      1.00      0.98        45

    accuracy                           0.92       130
   macro avg       0.79      0.79      0.79       130
weighted avg       0.92      0.92      0.92       130

